### ISSUE TITLE
Warning summary

### ISSUE THREAD

**Issue by macfire** [pytest-dev/pytest-flask#67] opened 2017-06-07 23:34 UTC
I am using the example tests in https://github.com/pytest-dev/pytest-flask/tree/master/tests

The tests runs fine, but includes 
```
========== warnings summary ===========
None
  Module already imported so can not be re-written: pytest_flask
  Module already imported so can not be re-written: _pytest.pytester
```

I found similar issue addressed here: https://github.com/pytest-dev/pytest/issues/2005
but am not understanding if there is a problem in one of the pytest packages or if I have my setup wrong?

**Comment by northernSage** [comment] 2020-10-06 00:52
Since I wasn't able to reproduce the warnings in our current release (1.0.0) I will close this. Feel free to open it if someone faces the same issue again.

**Closed by northernSage** 2020-10-06 00:52 UTC
